### PR TITLE
Avoid minimap2 break silently

### PR DESCRIPTION
**Pull request by miguelpmachado**

### CODE REVIEW

**Comment by giesselmann** [comment]
Hi Miguel,
looks good, before merging I have two questions:
Can you say when minimap2 is silently breaking as this is a bit concerning for me?
What do you think of deleting the {output}.log in the if statement and afterwards. Same function but keeps the workdir clean.
> if [ $(grep 'ERROR' {output}.log | wc -l) -gt 0 ]; then rm {output.log}; exit 1; fi
rm {output}.log

Pay

**Comment by miguelpmachado** [comment]
Hi Pay,
It breaks when it can't open the fastq files. I found that because I was cheating the Snakemake: I had a basecall made by a colleague that I wanted to reuse but not duplicate the files, so I symlink the sequences directory in my workspace to the original folder. But I forgot to add the original folder in the Singularity bindings. That made minimap2 breaks, but it exited with exit code 0 and created a sam file only with the header. I think you don't need to worry about this, because most of the users will not try to do what I did.
I missed the removal part because I'm used to work in the "shadow" and there I don't need to worry about temporary files. Sorry about that. I already change the code to remove the log file. I did it a little different. I hope it still fits what you want. I saw your message in the mail's preview and didn't notice you had included a suggestion.
Cheers,
Miguel

**Comment by giesselmann** [comment]
Merged. Let me know if you need it in master (latest) soon.
Otherwise I'm checking status of #16 and make a release later this month.
Thanks for the fix and explanation!
Pay

**Comment by miguelpmachado** [comment]
No worries. I changed it locally. But thanks for the attention.

**Pull request merged**
