### PR TITLE
Improve flexibility

### PR DESCRIPTION
**Pull request by miguelpmachado**
* Allow Singularity images specification through the env.yaml (useful when using local/centralized images);
  * Add threads as consumable resources (control the number of running jobs by the number of CPU usage);
  * Save guppy sequencing_summary.txt (useful to QA/QC the sequencing);
  * Reduce default assembly threads to a more reasonable value (I assumed 80 threads was a typo);
  * Add Slurm to profiles (and create a centralized cluster log folder);
  * Add report's missing dependency (seaborn package);

### CODE REVIEW

**Comment by giesselmann** [comment]
Hi Miguel,

First of all thank you for the pull request and time spent into development, this is very much appreciated!
For the future please split changes into individual commits, this makes the review/merge much easier.

The changes I would like to merge directly are:

- Add Slurm profile (can you add a slurm-jobscript.sh and rename scripts to slurm-status.py and slurm-submit.py for consistency)
- Add seaborn
- Also the cluster sub-folder for the logs is a great idea.

Would you mind adding the copyright/license header to the new files. Put your name under # Written by. I'll think of a contributor section in the docs to acknowledge external work.

These changes might need further discussion/explanation:

- guppy summary: Similar statistics are computed by the rule 'basecaller_stats' but independent of the basecaller. The idea of the pipeline is to produce only tool independent output formats. What column/metric would you want from the sequencing_summary.txt and is it possible to get this from the fastq after basecalling?

- asm threads: is intentionally that high and needed for human/mouse. Since nanopore is also often used on smaller genomes, maybe a good idea to lower this value.

These changes seem to be against the snakemake concept in my opinion:

- Singularity image specification: I would consider this one dangerous, as it allows the divergence of pipeline and container version. Also the version numbers need to be maintained and match the one in setup.py. What you might want to use instead is the --singularity-prefix which will save the images at a central location.

- Threads as consumables: I don't see a need for this so far. In local mode, --cores/ --jobs/ -j limits the number of threads used. In cluster mode, --local-cores limits the threads for localrules on the headnode and --jobs limits the number of jobs submitted in parallel. From my experience, the cluster queue/scheduler should handle load balancing while we submit everything we want to have computed. Limiting the number of jobs might be useful for I/O heavy jobs.


Pay

**Comment by giesselmann** [comment]
Hi Miguel,

any update on this? I'm preparing the next version on development branch, that's where the conflicts come from now.
I already included the missing seaborn and library into the container builds. These moved to Travis-CI, together with automated tests.

Pay

**Comment by miguelpmachado** [comment]
Hi @giesselmann,
Sorry for taking almost 1 month to come back to this.
>The changes I would like to merge directly are:
>
>Add Slurm profile (can you add a slurm-jobscript.sh and rename scripts to slurm-status.py and slurm-submit.py for consistency)
Add seaborn
Also the cluster sub-folder for the logs is a great idea.

Thanks for that. I already made the changes you asked.

>These changes might need further discussion/explanation:
>
>guppy summary: Similar statistics are computed by the rule 'basecaller_stats' but independent of the basecaller. The idea of the pipeline is to produce only tool independent output formats. What column/metric would you want from the sequencing_summary.txt and is it possible to get this from the fastq after basecalling?

I understand what you are saying, and unfortunately I don't know the software in detail to answer to you. I'm just the guy to whom it was asked to run several software to get some data (in terms of sequencing data and methylation). What I found is that the output produced/stored by nanopype was not enough to run other tools that uses a _sequencing_summary.txt_ like file (produced by Albacore and Guppy from what I understood). What I thought was to save this output in an optional manner (like using a optional flag in the config file).

>These changes might need further discussion/explanation:
>
>...
>
>asm threads: is intentionally that high and needed for human/mouse. Since nanopore is also often used on smaller genomes, maybe a good idea to lower this value.

I really thought it was a typo because I don't know anyone who have access to a machine with 80 threads/CPUs.

>These changes seem to be against the snakemake concept in my opinion:
>
>Singularity image specification: I would consider this one dangerous, as it allows the divergence of pipeline and container version. Also the version numbers need to be maintained and match the one in setup.py. What you might want to use instead is the --singularity-prefix which will save the images at a central location.

I understand what you are saying and I tried to find a way to deal with the version issue (with some automated way to get it in the config file), but I couldn't. The `--singularity-prefix` is not really an option to save images to a central location because hash names are not really manageable. It only works in the scoope of running things with Snakemake. But, again, I understand this is a difficult issue.

>These changes seem to be against the snakemake concept in my opinion:
>
>...
>
>Threads as consumables: I don't see a need for this so far. In local mode, --cores/ --jobs/ -j limits the number of threads used. In cluster mode, --local-cores limits the threads for localrules on the headnode and --jobs limits the number of jobs submitted in parallel. From my experience, the cluster queue/scheduler should handle load balancing while we submit everything we want to have computed. Limiting the number of jobs might be useful for I/O heavy jobs.

Here I have to disagree with you, because when you have different jobs using different threads you loose control on the number of threads/CPUs you are using in the cluster. With the `--cores`, `--jobs` or `-j` you just control what is the load you are putting in the queue, not in the cluster resources. With threads as consumables, you fully control the cluster resources you are using, which, in my opinion, is what you need.

Let me know what do you think about these. I bet you will have better solutions for these.

Thanks a lot.

Miguel

**Comment by giesselmann** [comment]
Hi Miguel,

no worries about time, I'm honestly very happy about external contribution.

- The slurm profile looks ready, very well done!
- The need for the guppy summary is okay, in the batches folder it is anyway considered tmp data. So let's also take that.
- I lowered the asm_threads to make the tests run within Travis. Our cluster is build of 80 and 128 core machines, now you know one who has these ;)
- the fasta index generation looks good! I wonder however, shouldn't nanopolish get the .fai as input? NGMLR shouldn't need it, right?

To go on from here:
I did a force push to development after you opened the pull request and also added some changes on the singularity back-end.
Can you first rebase your branch against origin/development in order to resolve the conflicts listed? Without conflicts the PR should also trigger a new Travis build.

Ideally I would like to release a new pipeline version this week already including some of your changes. 
Can we split the changes you made into two separate pull requests, keeping this one only for the changes listed above, and open a new one for the following changes:

- Singularity images: I agree that the hashes are not 'human compatible' and reviewing this, I see a gain also on the development side, if you can pin the images. I would review the code in the Snakemake again, also the entries from nanopype.yaml would need to be removed as the default should still be pulling images from docker-hub.

- Threads as consumables: I understand your point of threads in use versus jobs in queue. But isn't the aim of a cluster queue to balance the load across users? For debugging limiting the jobs in queue should still be sufficient to avoid canceling of thousands of jobs. 

For  a new pull request please do not squash all changes into a single commit, but group them by topic.

Thanks again for the time spent into this,

Pay

**Comment by miguelpmachado** [comment]
Ok, I'll rebase and do two different pull requests.

Regarding the threads as consumables, I'll give you an example to try to explain my point of view.
Imagine you have 15 nodes with 40 CPUs each and there are a lot of people using the cluster. You want to speed up your analysis but keeping resources available to other guys, so you decided to use only 40 CPUs (one node). Imagine that Guppy is the process that uses more resources, let's say 4 threads. Because you will only use 40 CPUs, you need to set the number of jobs to 10. But then you will only use 10 CPUs for processes that use 1 thread, missing the speed of running 40 processes with single threads.
This is why I thing using threads as consumables is useful. And you can use both things simultaneously. If you don't want to set the threads as resources, the number of jobs will still work. Maybe I can comment the resources part in the Slurm config to give the users the idea it is not mandatory.

Another thing, setting the output as piped will not use the resources wisely, because it will reserve the sum of threads of the rules grouped, but never made use of the total allocation at the same time. I seems to me that, in the case of nanopype, it is only useful to submit less jobs to the queue (it might be useful in other situations that I'm not visualizing at the moment).

Just to finish this topic of resources, I think rules should be shadowed as many as possible, because most of the clusters work with network file systems (which are slower than node's local disks, like /tmp ) and with shadow we can set rules to use local disks to speed up things a little bit. I tested shadow some rules, to check which were compatible with shadow, but I think I couldn't reach to a conclusion because of the pipe thing. I didn't tried to change the pipe and shadow because those things were not essencial for me to run nanopype in my cluster. But if you think it might be worth to change it, I'm happy to help you.

Regarding Singularity images, I didn't get how do you want to go for it. I checked the code and is still the same. Do you want me to make it conditional? Like `singularity: "docker://nanopype/alignment:{tag}".format(tag=config['version']['tag']) if config['singularity_images']['alignment'] is None else config['singularity_images']['alignment']`? And the user decides to specify it in the config or not. If this is the way to go, it might me useful to have it in nanopype.yaml commented, so the user knows it can be used.

What do you think?

**Comment by miguelpmachado** [comment]
I'll close this PR and create a new one.
Part of this PR is in https://github.com/giesselmann/nanopype/pull/11

**Comment by giesselmann** [comment]
Regarding pipes and shadowing:

The alignment module is implemented this way to allow different alignment rules to pipe into the same samtools sort. This was set up to avoid code duplication. While this could possibly be achieved differently, I think one extra thread for samtools view and sort is quite reasonable. 
Snakemake does still not support shadowing of group jobs. For the alignment there's two things to consider I guess. 
- First is samtools sort, this runs in the TMPDIR and I have to check if this uses the hosts' TMPDIR if you run the singularity workflow or a tmp within the container. In the second case sorting could end on a network storage which would hurt.
- Second: writing of the sorted bam file goes directly to the output (network) filesystem. From the load perspective this is the same compared to writing to /scratch and copying afterwards.

For the singularity:

The optional entry from you is good, should be commented in the PR to make docker pulls default.
If this goes into env.yaml (my favorite) the code below should do it. It could also go into nanopype.yaml, than the code below would always overwrite with the default values. 
```
#singularity_images:
#    - basecalling : '/path/to/local/basecalling.sif'
```

within the rules
```
singularity: config['singularity_images']['basecalling']
```
should be fine. I actually like this, as it moves the hardcoded docker paths to a single file. Makes it easier to maintain.

and within the main Snakefile
```
# I would put the list here and not parse the module names from the singularity subfolder
config['singularity_images'] = {module:
    "docker://nanopype/{module}:{tag}".format(tag=config['version']['tag'], module=module) for module in
    ['storage', 'basecalling', 'alignment', 'methylation', 'transcript', 'sv', 'demux']}


# the check if hasattr(workflow, 'use_singularity') and workflow.use_singularity:
# shouldn't be needed, Snakemake will decide if a rule is executed in a container

# to update from env.yaml:
config['singularity_images'].update(nanopype_env['singularity_images'] if 'singularity_images' in nanopype_env else {})
```

Maybe check if files are existing before updating the dict.

I wouldn't raise this warning:
```
print("[WARNING] No Singularity images were provided. Default ones will be used.", file=sys.stderr)
```
but only warn if an additional image is provided in the config, but the file is not found.

This method will always do a silent fallback to the default values, we can put one example in comments into the env.yaml and I can add a paragraph to the docs mentioning this feature.

What do you think about this?




For the threads:

Sorry for being a bit hesitant on new features, the aim is always to keep the pipeline slim, but the use case you mention makes sense to me now, so let's get it.

**Comment by miguelpmachado** [comment]
The solution for Singularity sounds nice. Do you implement that and I do the threads? [PR #11](https://github.com/giesselmann/nanopype/pull/11) or a new one?

**Comment by giesselmann** [comment]
Yes, perfect!
Open a new PR, I'm merging #11 as soon as the Travis build is done.
Can you also include the fasta index rule and adding the .fa.faidx to the nanopolish rule in the new PR?

**Comment by miguelpmachado** [comment]
I'll add the fasta index rule. But it has to be included both in _ngmlr_ (although not using it) and _methylation_nanopolish_ rules, otherwise the second _ngmlr_ run will always happened after _methylation_nanopolish_ runs.

I'll use this conversation to ask your opinion about _methylation_guppy_prob_threshold_. Do you have any idea what would be a reasonable value? By the way, it shouldn't be found in the _nanopype.yaml_ (at least commented)?

**Comment by giesselmann** [comment]
Ah I see, than we need to include the index into all alignment rules, since nanopolish could also run after minimap2 etc.

Guppy methylation calling is not ready and therefore undocumented. I tried to parse the output, but the resulting correlation with WGBS was very poor (but too good for a simple program error). I still have to check, what ONT is doing within their pipelines.

Also at the London Calling conference this year there was a poster comparing nanopore methylation detection. The order of tools (by _r_) is deepsignal (.92), nanopolish (.87), megalodon (.87), guppy (.84) and tombo (.74).
So getting deepsignal into the pipeline is high prio now. They need tensorflow though, which might interfer with the tensorflow for deepbinner in the demux module.
Still working on a way to handle conflicting python modules in the nanopype virtual env.

**Comment by miguelpmachado** [comment]
Got your point (for Guppy). Is the TensorFlow issue found in the _all_ image?
For the fasta index input (in alignment rules), it is only required for _ngmlr_ because is the only rule using reference directory as input (which cannot be modified after ngmlr run).

**Comment by giesselmann** [comment]
It's not an issue (yet) but since tensorflow moved from 1.x to 2.x (the pip package for 1 is tensorflow, for 2 it's either tensorflow or tensorflow-cpu) it is one of the packages likely causing trouble in the future.

**Pull request closed without merging**
