### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by miguelpmachado**
Following this pull request: https://github.com/giesselmann/nanopype/pull/10

Minor changes:
  * Add Slurm profile
  * Move MXQ logs to a cluster log directory
  * Guppy:
    * Save sequencing_summary.txt
    * Change shadow to minimal to really work in shadow directory

### CODE REVIEW

**Comment by giesselmann** [comment]
Very cool! Thank you!
The shadow='minimal' is breaking the basecalling test. I faced this in the past, with shallow it works, not exactly sure why.
But even with 'shallow' processing is done on the shadow and results are copied in the end.
Otherwise ready to merge.

**Comment by miguelpmachado** [comment]
Today I finished running Nanopype for 1064 fast5 in 7 days with 16 CPUs. And it run Guppy with shadow minimal. I don't understand why Travis failed! But I'm not used to Travis.
Do you want me to remove the shadow field?

**Comment by giesselmann** [comment]
It's not a travis issue. It seems to happen when the raw data archive is a relative path in the working directory.
Shallow is used for all raw-data rules, so keep it for guppy.

**Comment by miguelpmachado** [comment]
Ok. I usually miss the problems caused by relative paths because I always use absolute paths.

**Pull request merged**
